apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{.Values.serviceName}}
spec:
  host: {{.Values.serviceName}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL