replicaCount: 3
requestLimit: 1Gi
memoryLimit: 2Gi
requestcpu: 500m
cpulimit: 2
jaegertracing: "allinone"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  #targetMemoryUtilizationPercentage: 70
  
  
image:
  repository: registry-quay-rh-quay-registry.apps.idsstestmz.insight.local
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

namespace: "idss-microservice"
serviceName: "service-taxpayer-everification-din-business"
contextRoot: "evDin"
serviceType: "business-service"

jaegarImageUrl: registry.redhat.io/distributed-tracing/jaeger-agent-rhel8@sha256:e713c563702c53fbaa48902b73142aad3a58b2ba408402763acc4f8eae7cb129
jaegarUDPHostPort: dns:///allinone-collector-headless.idss-microservice.svc:14250
